ps4_controller_config: 
  ps4_interface: "/dev/input/js0"
  R2_max_val: 32767
  R2_min_val: -32767
  L2_max_val: 32767
  L2_min_val: -32767
ugv_config:
  # reverse and forward speed
  speed_max_val: 0.5
  speed_min_val: 0
